### ISSUE TITLE
ImportError: No module named inc.classes

### ISSUE THREAD

**Issue by wikijm** [Pepitoh/VBad#1]
When I launch "python VBad.py", I receive this error:
![vbad error](https://cloud.githubusercontent.com/assets/10724809/13728033/f9ebdaf6-e909-11e5-934d-059abc63f01b.PNG)

I precise that:

- All prerequisites have been installed

- I'm a beginner in Python, especially on Windows OS

- I'm assume that this error come from a misconfiguration on my side

Any help will be apreciated :-)

**Comment by Pepitoh** [comment]
Hi,

Just fixed __init__.py, should work now :-)

Thanks for your feedback!
