### ISSUE TITLE
Non-destructive markup

### ISSUE THREAD

**Issue by mattpalermo** [Pepitoh/VBad#12]
Firstly, very cool project! Thankyou.

Would I be able to markup my code for obfuscation such that the code will still function as normal before obfuscation? I am interested in how I could integrate this into my workflow. I would like to have the code permanently marked up so I don't have to repeat the fairly significant effort for each release (I like to release often). It doesn't seem possible with the current markup scheme described in the README.

**Comment by Pepitoh** [comment]
Hi,

I'm not sure i'm getting the whole point. 

> Would I be able to markup my code for obfuscation such that the code will still function as normal before obfuscation

The code stills function as normal once obfuscated (if there is no bug with obfuscation), no need to add markup for that :)

Please be more specifc, 

Thx ! 

Pepitoh

**Comment by mattpalermo** [comment]
Hi @Pepitoh,

I will try explain myself clearer:

While I am developing, I like to run my code to test if it works. For this to be as effective as possible, it would be best not to have to run VBad every time I want to run the VBA code. Instead I'd like to only run VBad every time I release a new version of the software product. Is there a way to mark up my code for VBad such that it will still run as normal even before I run VBad?

Thanks,
Matt

**Comment by Pepitoh** [comment]
I see your point, 

Unfortunatly it seems not possible. I did not found a way to markup your VBA so that it stills works without being launched with VBad. 

You can try to comment in a VBA way each markup, but not sure your vbad process will still work.

Pepitoh.

**Comment by mattpalermo** [comment]
Thanks. I might have a crack at trying to make it work one day.
