### ISSUE TITLE
not defined sub or fuction

### ISSUE THREAD

**Issue by gearcapitan** [Pepitoh/VBad#13]
No matter what type of macro it generates, it always gives me error of this type, which has not defined sub or fuction
![sin titulo](https://cloud.githubusercontent.com/assets/13740942/23143811/01e4f74a-f789-11e6-90f0-06e3226aacdf.png)

The macro by itself if it works, osea I mean before obfuscating, but already when I put it inside the vbad, for nothing the world works, it is always the same error, already tried with several types of macros and it is always the same

**Comment by Pepitoh** [comment]
Hi gearcapitan,

From what I see from the screen, you forgot to add a [rdm::xx] tag on your Auto_Open() (and verify that you had Auto_open as trigger_function in const.py).

If you not randomize your trigger function name, script will just add a garbage function or variable name in his Workbook_open() function, taht is why you get this error. 

Try it and keep inform. From what I see, you also have a problem with a string obfuscation, don't hesitate to use [!!] marker to avoid this kind a problem. I'm trying to imrove string obfuscation in release to come but it is not that easy.

Pepitoh.

**Comment by gearcapitan** [comment]
http://nodistribute.com/result/wva68XWuSsePD4zoh1bFNCU59t 
http://nodistribute.com/result/IRnZotpMVAFDSxsO1fzc
http://nodistribute.com/result/yXmIhdPCJx6Q1cHkjz7Yt89b2Mrin

Thanks, I already understood what I had to do, very good work, I hope it was not detected by avast, one of the most used antivirus :(

But it is already a fact that can make the macro work, I already have reverse connection and those things, thanks

**Comment by Pepitoh** [comment]
Oh great! do you have an idea why Avast is the only one to detect your file? What did you put in your malicious VBA? normaly, antivir will trigger on specific function name (such as VirtualProtect) which are not possible to obfuscate. 

But i've never seen only one match with Avast, i'm interesting !

Pepitoh

**Comment by Pepitoh** [comment]
I see. Do you have the signature trigger by Avast! ? It proably trigger on a function you use and that it is not randomizable, but i'm curious to know which one.

**Comment by gearcapitan** [comment]
no la tengo, y como te comentaba no importa que macro yo use, a todas les pasa lo mismo

**Comment by Pepitoh** [comment]
Ok, not realy VBAd issue here. I close
