### ISSUE TITLE
Quote into variable?

### ISSUE THREAD

**Issue by elenoir** [Pepitoh/VBad#19]
Hi,

First of all, thanks for you work, I discovered you tool by reading MISC :)

I have prepared my macro as suggested in the doc (cf demo_prepared.txt).
I have a randomized macro generated but in fact, it's not OK with syntax (cf demo_result.txt).
IMHO, it's because of "quote" inside the variable (it should break the detecting string regex) but I need them in the powershell command.
So my question is : how can I achieve what I want?

[demo_result.txt](https://github.com/Pepitoh/VBad/files/794921/demo_result.txt)

[demo_prepared.txt](https://github.com/Pepitoh/VBad/files/794912/demo_prepared.txt)

**Comment by elenoir** [comment]
I managed to do what I want by putting Chr(34) instead of quote.
Wait for a better idea is someone has :-)

**Comment by Pepitoh** [comment]
Hi elenoir .

Right on time :smile:. 
I commit the fix for quotes inside string yesterday evening (issue by telltell3). I tried with your demo_prepared.txt, everything sounds good now with this new commit.

Thx for the report,
