### ISSUE TITLE
2xDouble quotes in a WriteLine

### ISSUE THREAD

**Issue by crowface28** [Pepitoh/VBad#22]
VBad isn't properly handling 2xdouble quotes (to escape them) in a string passed to WriteLine.  Not sure what the issue is.

I've tried taking the 2xdouble quotes out, still no luck.  For example:
fileOut.WriteLine "myURL=""http://the.earth.li/~sgtatham/putty/latest/w32/putty.exe"""
creates this:
myURL=""http://the.earth.li/~sgtatham/putty/latest/w32/putty.exe""

The only solution I can think of is having a seperate .Write to print one quote before and after each string... that sounds like a pain.

**Comment by Pepitoh** [comment]
Hi crowface28,

Did you update script to last version? I already fix double quote probleme in this issue : #19 

Pepitoh.

**Comment by crowface28** [comment]
I'm on the latest version, I just downloaded and ran it today.

**Comment by crowface28** [comment]
This is some sample code that's giving me issues:
```
Sub [rdm::10]dropIt()
    Dim fso As Object
    Set [rdm::10]fso = CreateObject("Scripting.FileSystemObject")
    Dim Fileout As Object
    Set [rdm::10]Fileout = fso.CreateTextFile("C:\temp\out.txt", True, True)
    Fileout.Write "myURL=""http://the.earth.li/~sgtatham/putty/latest/w32/putty.exe"""
    Fileout.Close
End Sub

Sub [rdm::10]go()
	dropIt
End Sub
```

When the doc runs, it drops the string:
`myURL=""http://the.earth.li/~sgtatham/putty/latest/w32/putty.exe""`

It should drop it as such:
`myURL="http://the.earth.li/~sgtatham/putty/latest/w32/putty.exe"`

**Comment by Pepitoh** [comment]
Hi crowface28,

Thanks for the update. 

You are right, double quotes are included in final string which is not ok. 
I patch it in a new commit, deleting this 2xDouble quote in final ciphered string, tell me if it's ok 👍 

Pepitoh.

**Comment by Pepitoh** [comment]
I'm closing the issue, patch seems to be working.
