### ISSUE TITLE
avast detected

### ISSUE THREAD

**Issue by gearcapitan** [Pepitoh/VBad#25]
![windows 10 x64 avast-2017-04-14-11-10-43](https://cloud.githubusercontent.com/assets/13740942/25048635/08830b0c-2103-11e7-97e0-f334f1b7019f.png)

**Comment by gearcapitan** [comment]
Avast is the only one that detects the file 

http://nodistribute.com/result/7DslT0k6FNWYQae8A2SroEhgwm

**Comment by Pepitoh** [comment]
Again, won't fix. But thx for the update.
