### ISSUE TITLE
Ambiguous name detected 

### ISSUE THREAD

**Issue by bkr32** [Pepitoh/VBad#26]
when trying to enable macros in the generated files i get the error  "compilation error Ambiguous name detected" 
also how should i structure my vba script, when using my current vba (to obscure) i get the error "The trigger function name Test has not been found in the vba, triggering point cannot be set"

thanks

**Comment by Pepitoh** [comment]
Hi,

Sorry for the delay.

Everything is explain on the readme, did you check ? you need to indicate to VBad the name of the function you want to trigger. In your case, you did not change from the example and the function name is "Test". You should adjust to fit your needs.

Pepitoh

**Comment by bkr32** [comment]
i was able to get it to work, thanks for the great tool sorry i forgot to close the issue
