### ISSUE TITLE
Feeding VBS script?

### ISSUE THREAD

**Issue by danthegoodman1** [Pepitoh/VBad#28]
Is there anyway that I can just feed this VBS script? Or does the VBS script already need to be in a document? Also, I am getting 
`Traceback (most recent call last):
  File "VBad.py", line 3, in <module>
    import win32com.client, os
ImportError: No module named win32com.client`
every time I try to run it, even with using the default VBS script and word docs

**Comment by peneviper** [comment]
I can't get VBad to run am having this error "Traceback (most recent call last): File "VBad.py", line 3, in <module> import win32com.client, os ImportError: No module named win32com.client" what am i not doing right ???

Please Help

**Comment by Pepitoh** [comment]
Hi guys, 

Did you install pywin32? : https://sourceforge.net/projects/pywin32/
If yes, check your PATH and see if your module is installed correctly. You need this lib to use Office API.

**Comment by danthegoodman1** [comment]
Just installed it, testing now. Is there any way that this can work without having word/excel? Maybe instead of injecting it into the word/excel document for you it can just make another vbs file with the obfuscated and encrypted macro. Then it would just be an easy copy and paste into the word/excel document (and office then doesn't have to be installed on what ever machine).

**Comment by danthegoodman1** [comment]
Interesting, now I am getting: `Can't create vba module Rd, check if your template file is not modify or if you module name is ok, or if VBA project object model is activated on macro options`
keep in mind this is still me testing with the default files that come with the download.

**Comment by danthegoodman1** [comment]
and this keeps coming up with different 2 letters where `Rd` is, currently telling me `IT`

**Comment by danthegoodman1** [comment]
I am now getting the following error 
![capture](https://cloud.githubusercontent.com/assets/17806508/26209510/f9c8b5bc-3bba-11e7-9485-040487d0ec01.PNG)

**Comment by danthegoodman1** [comment]
And after running it again, I get this error: 
![capture1](https://cloud.githubusercontent.com/assets/17806508/26209781/be961be6-3bbb-11e7-9825-456a083cfbe8.PNG)
