### ISSUE TITLE
Trigger function name test has not been found 

### ISSUE THREAD

**Issue by peneviper** [Pepitoh/VBad#31]
Hello i must say thanks for you great work on VBad, i need your assistance i don't know where i will add the function name "Test" in my script, 

Error msg:
![image](https://cloud.githubusercontent.com/assets/18121741/26495241/bdb89df6-421a-11e7-8ad8-519695ec69af.png)

My script:
[vba_prepared.txt](https://github.com/Pepitoh/VBad/files/1031892/vba_prepared.txt)

pepitoh can you show me where i can add the function name in my attached script. Thanks

**Comment by Pepitoh** [comment]
Hi, 

Sorry for response time :)
You have to indicate your prepared vba which function you want to auto trigger.
In your example, I rename function "Document_open()" to Test(). You now have to indicate in const.py trigger_function_name = "Test".

Script will detect the function and antomaticly wrapped it in an auto trigger function. 

[vba_prepared.txt](https://github.com/Pepitoh/VBad/files/1087332/vba_prepared.txt)

Pepitoh
