### ISSUE TITLE
how to use 

### ISSUE THREAD

**Issue by johnjohny1990** [Pepitoh/VBad#36]
hi 
I dont khnow use this tool 
films about this not perfect
please help me

**Comment by ClaudyFaucan** [comment]
hellau
i am like johnjohny
help me pliz, i want to B an hacker

**Comment by Pepitoh** [comment]
![image](https://user-images.githubusercontent.com/15944951/31990144-8a359962-b974-11e7-9d6d-292e465cc99e.png)
