### ISSUE TITLE
run-time error -2146697211(800c0005)

### ISSUE THREAD

**Issue by johnjohny1990** [Pepitoh/VBad#37]
hi i create macro but when i perform it display error run-time error -2146697211(800c0005) "the system cannot locate the resource specified"
and when debug it display "microsoft word has stopped working"

**Comment by X0R1972** [comment]
hello everyone ..
Please can someone just give a little explain how to start VBad in cmd ..what command to use ?
i create a tmp file in C: and in tmp i put the VBad file ,after doing that am stuck in cmd not nowing where to start..
i asked before in issue but sadly not receive response ,so if someone can help.;thank you

**Comment by Pepitoh** [comment]
Please read Readme.
