### ISSUE TITLE
The Trigger Function name has not been found in the vba, trigger point cannot be set.

### ISSUE THREAD

**Issue by eternal1502** [Pepitoh/VBad#4]
I get this error on my windows command prompt. "The Trigger Function name has not been found in the vba, trigger point cannot be set." I dont know wat am doing wrong, as am just a beginner on Python. Any help please. Attached screenshot of the error. 

![screenshot_1](https://cloud.githubusercontent.com/assets/19981436/16150232/dc99fa08-348d-11e6-910b-3e2b2bd7d2d2.png)

**Comment by Pepitoh** [comment]
Same issue.
