### ISSUE TITLE
the owner do not give any full info about this tool

### ISSUE THREAD

**Issue by X0R1972** [Pepitoh/VBad#40]
I Have a lot of trouble with this tool and see in Issues that im not alone 
it's sad that the guy who create it dont give more info about it..
there is no info where to start , how to create a full obfuscate ..and more 
So it have no point to put a tool  here that not work !

**Comment by nadouani** [comment]
@mateo24xx did you take few seconds to read that https://github.com/Pepitoh/VBad#how-it-works?

**Comment by Pepitoh** [comment]
@mateo24xx, 
All required information to make VBad work are in the Readme.

If you do not manage to make it work, don't blame me and think harder. There is no point to use tool that you do not understand.

Read this:
https://www.python.org/about/gettingstarted/
https://msdn.microsoft.com/en-us/library/office/ee814737(v=office.14).aspx

**Comment by X0R1972** [comment]
friend sorry but i now how it works,that's not my question  what i want to say it is that i have full errors 
i tried a lot of things but still not functionning good 
i tested in windows 10.;windows 7 
with linux and with windows.
