### ISSUE TITLE
kan you make youtube clip :) how to 

### ISSUE THREAD

**Issue by vasco2016** [Pepitoh/VBad#6]

**Comment by HackM3nt3** [comment]
Please don't make the video, that would kill the tool, every script kiddie will be use it.

**Comment by legendary77** [comment]
> Please don't make the video, that would kill the tool,...

I am of the same opinion as you, but less brings me the solution by writing me sasuke46@hotmail.fr

thank you

**Comment by Pepitoh** [comment]
Hi,
I think the wiki speaks for itself :smile:
Flo.
