### ISSUE TITLE
Thanks you bro

### ISSUE THREAD

**Issue by legendary77** [Pepitoh/VBad#7]
Thanks you

    __     ______            _
    \ \   / / __ )  __ _  __| |
     \ \ / /|  _ \ / _` |/ _` |
      \ V / | |_) | (_| | (_| |
       \_/  |____/ \__,_|\__,_|

            VBA Obfuscation Tools combined with an MS office document generator
            By @Pepitoh

**Comment by Pepitoh** [comment]
You're welcome !
